# Form implementation generated from reading ui file 'UI/design/frameDisplay.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FrameDisplay(object):
    def setupUi(self, FrameDisplay):
        FrameDisplay.setObjectName("FrameDisplay")
        FrameDisplay.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(FrameDisplay)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(FrameDisplay)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(FrameDisplay)
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(FrameDisplay)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 0, 1, 1)

        self.retranslateUi(FrameDisplay)
        QtCore.QMetaObject.connectSlotsByName(FrameDisplay)

    def retranslateUi(self, FrameDisplay):
        _translate = QtCore.QCoreApplication.translate
        FrameDisplay.setWindowTitle(_translate("FrameDisplay", "Frame Display"))
        self.pushButton_2.setText(_translate("FrameDisplay", "Show Timestamp"))
        self.pushButton.setText(_translate("FrameDisplay", "Display in Separate Windows"))
        self.pushButton_3.setText(_translate("FrameDisplay", "Show Frame Index"))
